{
    "Human Genetics": ["BIOL 1318", "3", "Lower Division"],
    "Body Systems": ["BIOL 1350", "3", "Lower Division"],
    "Topics in Biological Sciences": ["BIOL 3V00", "1-6", "Upper Division"],
    "Topics in Biological Sciences with Lab": ["BIOL 4V01", "1-6", "Upper Division"],
    "Individual Instruction in Biology": ["BIOL 2V95", "1-6", "Lower Division"],
    "Introduction to Modern Biology Workshop I": ["BIOL 2111", "1", "Lower Division"],
    "Introduction to Modern Biology Workshop II": ["BIOL 2112", "1", "Lower Division"],
    "Introductory Biology Laboratory": ["BIOL 2281", "2", "Lower Division"],
    "Introduction to Modern Biology I": ["BIOL 2311", "3", "Lower Division"],
    "Introduction to Modern Biology II": ["BIOL 2312", "3", "Lower Division"],
    "Biological Basis of Health and Disease": ["BIOL 2350", "3", "Lower Division"],
    "Course-based Undergraduate Research Experience in Biology": [
        "BIOL 2V81",
        "2-3",
        "Lower Division",
    ],
    "Undergraduate Research in Biology": ["BIOL 3V91", "1-3", "Upper Division"],
    "Introduction to Microbiology Lab": ["BIOL 3203", "2", "Upper Division"],
    "Introduction to Microbiology": ["BIOL 3303", "3", "Upper Division"],
    "Evolutionary Analysis": ["BIOL 3305", "3", "Upper Division"],
    "Parasitology": ["BIOL 3306", "3", "Upper Division"],
    "Programming for Biological Sciences": ["BIOL 3312", "3", "Upper Division"],
    "Discrete Biomedical Systems": ["BIOL 3314", "3", "Upper Division"],
    "Epigenetics": ["BIOL 3315", "3", "Upper Division"],
    "Forensic Biology": ["BIOL 3318", "3", "Upper Division"],
    "Applied Genetics": ["BIOL 3320", "3", "Upper Division"],
    "Ecosystems": ["BIOL 3322", "3", "Upper Division"],
    "Drug Development to Clinical Trials": ["BIOL 3325", "3", "Upper Division"],
    "Microbial Physiology": ["BIOL 3335", "3", "Upper Division"],
    "Protein and Nucleic Acid Structure": ["BIOL 3336", "3", "Upper Division"],
    "Bioinformatics": ["BIOL 3337", "3", "Upper Division"],
    "Clinical Pathophysiology": ["BIOL 3355", "3", "Upper Division"],
    "Mammalian Physiology with Lab": ["BIOL 3357", "3", "Upper Division"],
    "Exercise Physiology": ["BIOL 3370", "3", "Upper Division"],
    "Comparative Physiology": ["BIOL 3372", "3", "Upper Division"],
    "Biochemistry Laboratory": ["BIOL 3380", "3", "Upper Division"],
    "Medical Histology": ["BIOL 3385", "3", "Upper Division"],
    "Honey Bee Biology": ["BIOL 3388", "3", "Upper Division"],
    "Biological Barriers": ["BIOL 3398", "3", "Upper Division"],
    "Genetics": ["BIOL 3401", "4", "Upper Division"],
    "Molecular and Cell Biology": ["BIOL 3402", "4", "Upper Division"],
    "Systems Biology": ["BIOL 3413", "4", "Upper Division"],
    "Human Anatomy and Physiology with Lab I": ["BIOL 3455", "4", "Upper Division"],
    "Human Anatomy and Physiology with Lab II": ["BIOL 3456", "4", "Upper Division"],
    "Biochemistry I": ["BIOL 3461", "4", "Upper Division"],
    "Biochemistry II": ["BIOL 3462", "4", "Upper Division"],
    "Research Practicum for UT-PACT": ["BIOL 3V15", "1-6", "Upper Division"],
    "Topics in Molecular and Cell Biology": ["BIOL 3V40", "1-6", "Upper Division"],
    "Undergraduate Readings in Biology": ["BIOL 3V90", "1-3", "Upper Division"],
    "Undergraduate Research in Biochemistry": ["BIOL 3V93", "1-3", "Upper Division"],
    "Topics in Biology: Individual Instruction": ["BIOL 3V94", "1-6", "Upper Division"],
    "Undergraduate Research in Molecular and Cell Biology": [
        "BIOL 3V96",
        "1-3",
        "Upper Division",
    ],
    "Undergraduate TA Apprenticeship": ["BIOL 4002", "0", "Upper Division"],
    "Course-based Undergraduate Research Experience in Molecular Neuropathology": [
        "BIOL 4156",
        "1",
        "Upper Division",
    ],
    "TA Apprenticeship": ["BIOL 4302", "3", "Upper Division"],
    "Molecular Evolution": ["BIOL 4305", "3", "Upper Division"],
    "Developmental Biology": ["BIOL 4308", "3", "Upper Division"],
    "Cellular Microbiology": ["BIOL 4310", "3", "Upper Division"],
    "Cellular and Molecular Medicine of Human Diseases": [
        "BIOL 4317",
        "3",
        "Upper Division",
    ],
    "Nutrition and Metabolism": ["BIOL 4325", "3", "Upper Division"],
    "Advanced Research in Molecular and Cell Biology": [
        "BIOL 4330",
        "3",
        "Upper Division",
    ],
    "Seminal Papers in Biology": ["BIOL 4337", "3", "Upper Division"],
    "Genomics": ["BIOL 4341", "3", "Upper Division"],
    "Immunobiology": ["BIOL 4345", "3", "Upper Division"],
    "Medical Microbiology": ["BIOL 4350", "3", "Upper Division"],
    "Molecular Biology of HIV/AIDS": ["BIOL 4353", "3", "Upper Division"],
    "Molecular Neuropathology": ["BIOL 4356", "3", "Upper Division"],
    "Molecular Neuropathology II": ["BIOL 4357", "3", "Upper Division"],
    "Evolution and Development": ["BIOL 4360", "3", "Upper Division"],
    "Advanced Human Physiology": ["BIOL 4365", "3", "Upper Division"],
    "Molecular Biology of Cancer": ["BIOL 4366", "3", "Upper Division"],
    "General and Molecular Virology": ["BIOL 4371", "3", "Upper Division"],
    "Cell and Molecular Biology Laboratory": ["BIOL 4380", "3", "Upper Division"],
    "Oral Histology and Embryology": ["BIOL 4385", "3", "Upper Division"],
    "Senior Readings in Molecular and Cell Biology": [
        "BIOL 4390",
        "3",
        "Upper Division",
    ],
    "Senior Research in Molecular and Cell Biology": [
        "BIOL 4391",
        "3",
        "Upper Division",
    ],
    "Senior Honors Research for Thesis in Molecular and Cell Biology": [
        "BIOL 4399",
        "3",
        "Upper Division",
    ],
    "Biophysical Chemistry": ["BIOL 4461", "4", "Upper Division"],
    "Special Topics in Biology": ["BIOL 4V00", "1-6", "Upper Division"],
    "Special Topics in Molecular and Cell Biology": [
        "BIOL 4V40",
        "1-6",
        "Upper Division",
    ],
    "Clinical Research Lab": ["BIOL 4V81", "1-3", "Upper Division"],
    "Advanced Topics in Biology": ["BIOL 4V95", "Individual", "Upper Division"],
    "Senior Honors Research in Molecular and Cell Biology": [
        "BIOL 4V99",
        "3-6",
        "Upper Division",
    ],
}
